services:
  api:
    build: .
    image: buscacursosapi-image
    container_name: buscacursosapi-container
    expose:
      - "8000"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run api
    environment:
      - TUNNEL_ORIGIN_CERT=/etc/cloudflared/cert.pem
    volumes:
      - /home/ubuntu/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - api
    restart: unless-stopped
