services:
  buscacursosapi:
    build: .
    image: buscacursosapi-image
    container_name: buscacursosapi-container
    expose:
      - "8000"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run api
    volumes:
      - /home/ubuntu/.cloudflared:/etc/cloudflared:ro
    depends_on:
      - buscacursosapi
    restart: unless-stopped
